# Generated by Django 6.0 on 2026-01-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains_and_cereals', 'Grains_&_Cereals'), ('pulses_and_legumes', 'Pulses_&_Legumes'), ('spices_and_herbs', 'Spices_&_Herbs'), ('dairy_and_oils', 'Dairy_&_Oils')], max_length=50, null=True),
        ),
    ]
