# Generated by Django 6.0 on 2026-01-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains_and_cereals', 'Grains_and_Cereals'), ('pulses_and_legumes', 'Pulses_and_Legumes'), ('spices_and_herbs', 'Spices_and_Herbs'), ('dairy_and_oils', 'Dairy_and_Oils')], max_length=50, null=True),
        ),
    ]
