# Generated by Django 6.0 on 2026-01-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains_and_cereals', 'Grains & Cereals'), ('pulses_and_legumes', 'Pulses & Legumes'), ('spices_and_herbs', 'Spices & Herbs'), ('dairy_and_oils', 'Dairy & Oils')], max_length=50, null=True),
        ),
    ]
