# Generated by Django 6.0 on 2026-01-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains', 'Grains'), ('cereals', 'Cereals'), ('pulses', 'Pulses'), ('spices', 'Spices'), ('herbs', 'Herbs'), ('dairy', 'Dairy'), ('oils', 'Oils')], max_length=50, null=True),
        ),
    ]
